### ISSUE TITLE
Could you provide me an example of the plugin project,I try to write one , but Sync tells me "Value can not be null ,Variable element"

### ISSUE THREAD

**Issue by Someone999** [OsuSync/SyncPlugin#29]

**Comment by Someone999** [comment]
Only need the necessary operations.

**Comment by Someone999** [comment]
Only need the necessary code.

**Comment by MikiraSora** [comment]
https://github.com/OsuSync/SyncDevTutorial

**Comment by Someone999** [comment]
Thank you

**Comment by Someone999** [comment]
I followed that made on , but the Sync told me "插件Plugin 非osuSync插件 (值不能为 null。
参数名: element)"

**Comment by Someone999** [comment]
What the element is?

**Comment by KedamaOvO** [comment]
This is generally your plugin throwing an exception in the constructor.

**Comment by Someone999** [comment]
I added the try-catch to my constuctor, them can not catch any exception.

**Comment by Someone999** [comment]
And I use it by reference, no exception be thrown.

**Comment by KedamaOvO** [comment]
Try adding try-catch to OnEnable.

**Comment by Someone999** [comment]
I only override OnEnable , Is it necessary to override OnDisable and OnExit ?

**Comment by Someone999** [comment]
But it's almost no possibility to throw any exception in OnEnable and PluingEventInit, unless I can not use Sync's IO before Init.

**Comment by Someone999** [comment]
void Init(PluginEvents.InitPluginEvent e)
        {
                IO.CurrentIO.WriteColor("Init!", ConsoleColor.Red);
        }

public override void OnEnable()
        {
                IO.CurrentIO.WriteColor("Enabled", ConsoleColor.White);  
        }

**Comment by Someone999** [comment]
This two functions

**Comment by KedamaOvO** [comment]
Use this sync. It can print stack trace. 
https://pan.baidu.com/s/1lozwBA5oDJOKTC-S2oaSdA dk8x

**Comment by Someone999** [comment]
在 System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   在 System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   在 Sync.Plugins.PluginManager.CheckIsReferenceTo(Type a, String b)
   在 Sync.Plugins.PluginManager.LateLoad(Type a)
   在 Sync.Plugins.PluginManager.layerLoader(IList`1 asmList)

**Comment by Someone999** [comment]
插件Plugin 非osuSync插件 (值不能为 null。
参数名: element)
[15:56:05]    在 System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   在 System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   在 Sync.Plugins.PluginManager.CheckIsReferenceTo(Type a, String b)
   在 Sync.Plugins.PluginManager.LateLoad(Type a)
   在 Sync.Plugins.PluginManager.layerLoader(IList`1 asmList)

**Comment by Someone999** [comment]
An attribute?

**Comment by KedamaOvO** [comment]
Have you used the SyncPluginDependency feature?

**Comment by Someone999** [comment]
Wait a minute , I ready to upload my project to GitHub , could you help me to find out the problem ?

**Comment by KedamaOvO** [comment]
No problem.

**Comment by Someone999** [comment]
https://github.com/Someone999/TestPlugin/tree/master
But I don't know can you see this.

**Comment by KedamaOvO** [comment]
I can't access, is this a private repo?

**Comment by Someone999** [comment]
OK,I will set it

**Comment by Someone999** [comment]
You can try again now. I had changed the status before this ,it's seems like failed.

**Comment by KedamaOvO** [comment]
![image](https://user-images.githubusercontent.com/9410177/56847366-75e55a80-690c-11e9-9c69-60146ad14443.png)
The GUID of SyncPluginDependency is the GUID of the dependent plugin. 
If there is no dependency, you don't need to declare this attribute.
SyncPluginID is same.
![image](https://user-images.githubusercontent.com/9410177/56847478-e93b9c00-690d-11e9-88cc-c3dc16ea8aac.png)
All GUIDs you can find in https://github.com/OsuSync/SyncPlugin/issues. 

Plugin "{Plguin Name}" Authorize Request:
![image](https://user-images.githubusercontent.com/9410177/56847505-391a6300-690e-11e9-91c1-e5bcc079c42d.png)

**Comment by KedamaOvO** [comment]
This is a small plugin that should help you.
https://github.com/KedamaOvO/RealTimePPJsFormatter/blob/master/RealTimePPJsFormatterPlugin.cs

**Comment by Someone999** [comment]
Can I use it without GUID , I don't want to release it.

**Comment by KedamaOvO** [comment]
yes, you can.

**Comment by Someone999** [comment]
I got that

**Comment by Someone999** [comment]
I deleted that two Attributes , it's work ,thank you.

**Comment by Someone999** [comment]
There a another problem, I can not use configgui  if my plugin exists , how can I do to avoid that?

**Comment by KedamaOvO** [comment]
Does configgui throw an exception?

**Comment by Someone999** [comment]
Yes, I had questioned you about the same exception for some weeks , at that time ,you told me that may be result in by some plugins in the plugin list.

**Comment by KedamaOvO** [comment]
Can you give me your plugin?

**Comment by Someone999** [comment]
The website yesterday I gave you , I have not change it yet.

**Comment by Someone999** [comment]
Or the dll file?

**Comment by KedamaOvO** [comment]
I can't compile this repo, please give me the dll file. 😥

**Comment by Someone999** [comment]
ok, Sorry about reply late.

**Comment by Someone999** [comment]
[ConsoleApp1.zip](https://github.com/OsuSync/SyncPlugin/files/3124766/ConsoleApp1.zip)

**Comment by KedamaOvO** [comment]
need osutools.dll

**Comment by Someone999** [comment]
[Plugins.zip](https://github.com/OsuSync/SyncPlugin/files/3125322/Plugins.zip)

**Comment by Someone999** [comment]
This Dll is used to get Info from ortdp and mmf created by RTPPD.

**Comment by Someone999** [comment]
osuTools.SyncInfo.GetInfo() is a Event need bind to Timer.Tick

**Comment by Someone999** [comment]
I can not get right value if GetInfo Run in Sync , if my plugin's mmf reader read faster than RTPPD's writer?

**Comment by Someone999** [comment]
And GetInfo is not a static function

**Comment by KedamaOvO** [comment]
You need to use "SyncPluginDependency" or "SyncSoftRequirePlugin" to tell Sync your plugin's dependencies so that Sync determines the order in which the plugins are loaded.
![image](https://user-images.githubusercontent.com/9410177/56875851-dc39bc80-6a75-11e9-96b8-0a24b613efb4.png)
![image](https://user-images.githubusercontent.com/9410177/56875855-e78ce800-6a75-11e9-8178-8be8e7262f75.png)

**Comment by Someone999** [comment]
I can not view the image, and I added that before my class
like
namespace x
{
[SyncPluginDependency("")]
class MyPlugin:Plugin
//...
}

 , when loading plugins, my plugin threw NullReferenceException

**Comment by Someone999** [comment]
[SyncPluginDependency("8eb9e8e0-7bca-4a96-93f7-6408e76898a9")]

**Comment by Someone999** [comment]
umm...We can communicate with Chinese, right?

**Comment by KedamaOvO** [comment]
This is a Sync bug, and now you can use a temporary solution like this.
```csharp
    [SyncPluginDependency("8eb9e8e0-7bca-4a96-93f7-6408e76898a9", Version = "^1.7.0", Require = true)]
    [SyncPluginID("-1","0.0.1")]
    public partial class P : Plugin{}
```

**Comment by KedamaOvO** [comment]
```csharp
public override void OnEnable()
{
    var gui = getHoster().EnumPluings().FirstOrDefault(p => p.Name == "ConfigGUI");
    if (gui is ConfigGuiPlugin configGui)
    {
        configGui.ItemFactory.RegisterItemCreator<YourCustomAttribute>(new YourCustomAttributeCreator());
        //TODO
    }
}
```

**Comment by Someone999** [comment]
So , all the size and position need to calculated by self. And it's seems like add a control dynamically in a normal window.

**Comment by KedamaOvO** [comment]
No, WPF can automatically calculate the position and size, but generally it won't look good.
If you need a visual layout, you can create a window and open it in btn.Click .
```csharp
Button btn = new Button();
btn.Click+=(s,e)=>{
    var win = new YourWindow();
    win.Show();
};
```

**Comment by Someone999** [comment]
How can I understand the attributes (like StringAttribute) in configgui?

**Comment by KedamaOvO** [comment]
It tells ConfigGUI what Creator should be used for this item.
```
StringAttribute <=> StringConfigurationItemCreator
BoolAttribute <=> BoolConfigurationItemCreator
FloatAttribute <=> FloatConfigurationItemCreator
...
```

**Comment by Someone999** [comment]
What will it do if inherit the base class?

**Comment by Someone999** [comment]
I mean that the class inherit base class is not a native Sync class

**Comment by KedamaOvO** [comment]
Need to call **configGui.ItemFactory.RegisterItemCreator\<YourCustomAttribute\>(new YourCustomAttributeCreator())** to establish a mapping.
If the map does not exist, an exception will be thrown.
![image](https://user-images.githubusercontent.com/9410177/57570812-d9a57280-7438-11e9-9cf1-f7616a5a3c48.png)


This is the default mapping for ConfigGUI.
![image](https://user-images.githubusercontent.com/9410177/57570763-23418d80-7438-11e9-96ec-0aee2ba10350.png)

**Comment by Someone999** [comment]
Must attributes match with the type of setting items

**Comment by Someone999** [comment]
By the way , what will function "bool Check(string)" do

**Comment by Someone999** [comment]
Although the name is obviously mean that is used to check, but what's that argument used to do?

**Comment by KedamaOvO** [comment]
```csharp
bool Check(string str)
```
Used to check if str matches the format.
At this point str is the value in the key-value pair in Config.ini.

```
PPFontSize = 20
```
```csharp
[Integer(MinValue = 10,MaxValue = 150)]
public ConfigurationElement PPFontSize{get; set; }
```
now, str is "20"

```csharp
    public class FloatAttribute : BaseConfigurationAttribute
    {
        public float MinValue { get; set; } = float.MinValue;
        public float MaxValue { get; set; } = float.MaxValue;
        public float Step { get; set; } = 1;

        public override bool Check(string str)
        {
            if (!float.TryParse(str, out float v))
                return false;
            return (MinValue <= v && v <= MaxValue);
        }
    }
```

**Comment by Someone999** [comment]
Could you help me to correct my plugin? I can not use that because the Exception
`namespace ConsoleApp1
{
    using System.Reflection;
    using System.Windows.Controls;
    using ConfigGUI.ConfigurationRegion.ConfigurationItemCreators;
    using Sync.Tools.ConfigurationAttribute;
    using Sync.Tools;
    class GUIConfigCreator:StringConfigurationItemCreator
    {
        TextBox tx;
       
        public override Panel CreateControl(BaseConfigurationAttribute attr, PropertyInfo prop, object configuration_instance)
        {
            var pa = base.CreateControl(attr, prop, configuration_instance);
            Label l = new Label
            {
                Content = "InfoReader文件路径",
                Margin = new System.Windows.Thickness(1, 5, 0, 0),
                Height = 5,
                Width=15
            };
           tx = new TextBox
            {
                Text = "C:\\Users\\add\\Documents\\Visual Studio 2017\\project\\ortdp test\\ortdptest\\bin\\Release\\ortep test.exe",
                Margin = new System.Windows.Thickness(25, 15, 0, 0),
                Height = 5,
                Width = 100
            };
            Button b = new Button
            {
                Margin = new System.Windows.Thickness(140, 20, 0, 0),
                Height = 5,
                Width=10,
                Content = "浏览"
            };
            b.Click += B_Click; ;
            pa.Children.Add(l);
            pa.Children.Add(tx);
            pa.Children.Add(b);
            l.Visibility = System.Windows.Visibility.Visible;
            tx.Visibility = System.Windows.Visibility.Visible;
            b.Visibility = System.Windows.Visibility.Visible;
            return pa;
        }

        private void B_Click(object sender, System.Windows.RoutedEventArgs e)
        {
            System.Windows.Forms.OpenFileDialog openfile = new System.Windows.Forms.OpenFileDialog();
            openfile.Filter = "可执行文件|*.exe";
            openfile.ShowDialog();
            if(openfile.FileName!="")
            {
                
                tx.Text = openfile.FileName;
            }
        }
    }
    class GUIConfig:StringAttribute
    {
        public GUIConfig()
        {

        }
        public override bool Check(string value)
        {
            
           if(System.IO.File.Exists(value))
            {
                return true;
            }
           else
            {
                return false;
            }
        }
    }
}`

**Comment by KedamaOvO** [comment]
You need call configGui.ItemFactory.RegisterItemCreator<GUIConfig>(new GUIConfigCreator()).
And you can use PathAttribute.

**Comment by Someone999** [comment]
I had called it in constructor.

**Comment by Someone999** [comment]
Use StringAttribute

**Comment by KedamaOvO** [comment]
Can you tell me more exception information?

**Comment by Someone999** [comment]
[22:55:32] “ConfigGUI.ConfigWindow”的类型初始值设定项引发异常。
[22:55:32]    在 ConfigGUI.ConfigWindow..ctor(ConfigurationItemFactory itemFactory)
   在 ConfigGUI.ConfigGuiPlugin.<>c__DisplayClass7_0.<OnEnable>b__3()
   在 System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback)
   在 ConfigGUI.ConfigGuiPlugin.<>c__DisplayClass7_0.<OnEnable>b__2(Arguments args)
   在 Sync.Command.CommandDispatch.invoke(String name, Arguments args)
[22:55:32] ConfigGUI
[22:55:32] 命令执行失败！ 请输入help查看命令列表。

**Comment by KedamaOvO** [comment]
Can you give me the plugin dll or source code?

**Comment by Someone999** [comment]
[ConsoleApp1.zip](https://github.com/OsuSync/SyncPlugin/files/3170284/ConsoleApp1.zip)
A hole project is here.

**Comment by KedamaOvO** [comment]
[ConfigGUI.zip](https://github.com/OsuSync/SyncPlugin/files/3170356/ConfigGUI.zip)
fixed.

**Comment by Someone999** [comment]
I see, thank you

**Comment by Someone999** [comment]
Could you tell me how to convert the string in Textbox to a value of field(Like RTPPD).

**Comment by Someone999** [comment]
I knew that one of the way is reflection, is other way to get that?

**Comment by KedamaOvO** [comment]
> Could you tell me how to convert string to the value of field(Like RTPPD).

1. Manually write conversion code.
2. Use a serialization library.(e.g. NewtonSoft.Json)

**Comment by Someone999** [comment]
Can I avoid this?
![批注 2019-05-13 220131](https://user-images.githubusercontent.com/45456778/57627576-d04c0f80-75ca-11e9-8e4a-a2d1104f55b1.jpg)

**Comment by Someone999** [comment]
Because this and Sync doesn't copy the non-dll files, I can not debug my plugin by debugger and pdb file.

**Comment by KedamaOvO** [comment]
View the call stack.
You can copy pdf using "project"->"properties"->"build event".

**Comment by Someone999** [comment]
![批注 2019-05-13 222451](https://user-images.githubusercontent.com/45456778/57629196-f9ba6a80-75cd-11e9-859d-a5debd51c2b8.jpg)
Call Stack is here

**Comment by KedamaOvO** [comment]
Can you give me the plugin dll or source code?
![7U1TOKWMW88Y@5A1M}BH$1E](https://user-images.githubusercontent.com/9410177/57633173-b663fa00-75d5-11e9-93d4-2dc0ba4a4f9e.jpg)

**Comment by Someone999** [comment]
I think ... it is OsuRTDataProviderRelease.dll

**Comment by Someone999** [comment]
The exception be thrown when I call OnEnable() of OsuRTDataProvider

**Comment by Someone999** [comment]
if I press continue 
![image](https://user-images.githubusercontent.com/45456778/57634248-861d5b00-75d7-11e9-9297-1a93c6d9cc72.png)

**Comment by KedamaOvO** [comment]
I guess it may be a thread conflict between multiple ORTDP instances.

**Comment by Someone999** [comment]
By the way , I the framework is preview version 4.7.3 (maybe)

**Comment by Someone999** [comment]
Will it leads in this?

**Comment by KedamaOvO** [comment]
I don't know, but you can try to downgrade to 4.5.

**Comment by Someone999** [comment]
It seems like the target framework version of OsuRTDataProvider is higher than 4.5

**Comment by Someone999** [comment]
I set my project's target version to 4.5, than it can not use OsuRTDataProvider

**Comment by Someone999** [comment]
The lowest available version is 4.6.1 with OppaiWNet

**Comment by KedamaOvO** [comment]
ORTDP is 4.5.2.
OppaiWNet is 4.6.1

**Comment by Someone999** [comment]
But it is not a big problem, only need add try-catch

**Comment by Someone999** [comment]
I saw that , only .NET Core and it's Runtime is preview version

**Comment by Someone999** [comment]
I tried to show a window, but no sooner as it start , that window have no response.

**Comment by Someone999** [comment]
Window is WinForm Window
Use Command to show.
Only new and show in the code.

**Comment by Someone999** [comment]
Window Class constructor only calls InitializeComponent().

**Comment by Someone999** [comment]
When the time will occurs this?
未经处理的异常:  System.IO.FileLoadException: 未能加载文件或程序集“Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
I watched the version, dll version is 7.0.1.18622 reference version is 7.0.0.0 what should I do?

**Comment by Someone999** [comment]
未经处理的异常:  System.IO.FileLoadException: 未能加载文件或程序集“Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
Why it happened? It is suddenly happens after a restart of Sync, that time I modified my plugin. After that, I tried to rollback, but this exception be thrown again and again.
I saw the version, dll version is 7.0.1.18622 reference version is 7.0.0.0 what should I do?

**Comment by KedamaOvO** [comment]
Install Newtonsoft.Json using nuget.
{your project}->right click->nuget

**Comment by Someone999** [comment]
I tried to show a window, but as soon as it shows, the window hung on.

**Comment by Someone999** [comment]
Window is WinForm Window
Only new and show in the code.

**Comment by KedamaOvO** [comment]
You need to use WPF.
If you use WinForm you need to ensure that there is an extra thread for running the event loop of WinForm.
like this.
https://github.com/OsuSync/SyncPlugin/blob/f9d50a154f926b9d8d76f09f3dd52a097eb36ebd/DefaultGUI/DefaultGUI.cs#L41-L43
https://github.com/OsuSync/SyncPlugin/blob/f9d50a154f926b9d8d76f09f3dd52a097eb36ebd/DefaultGUI/DefaultGUI.cs#L76-L84

**Comment by Someone999** [comment]
I forgot that Windows uses Message to tell window how to do.

**Comment by Someone999** [comment]
If I close my window , it's can not show again. If I hide that(Cancel Close Event and Hide the window),
I can not enter and exec command in Sync

**Comment by Someone999** [comment]
And Output is work normally .

**Comment by Someone999** [comment]
Window is WinForm Window
Event Func
private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            e.Cancel = true;
            Hide();
        }

**Comment by Someone999** [comment]
Who maintenance the plugin "ImageOverlay" now?You or Deliay? I have an issue. If the answer is you , the issue is the display window flashes in OBS record.

**Comment by KedamaOvO** [comment]
> Who maintenance the plugin "ImageOverlay" now?You or Deliay? I have an issue. If the answer is you , the issue is the display window flashes in OBS record.

check GameSource->"Capture third-party overlays"
![image](https://user-images.githubusercontent.com/9410177/57770027-f2b46900-7741-11e9-86ea-41d14381ea46.png)

**Comment by Someone999** [comment]
I created my window successfully and can operate ,but if I close my window , it's can not show again. If I hide that(Cancel Close Event and Hide the window),
I can not enter and exec command in Sync
Window is WinForm Window
Event Func
private void Form1_FormClosing(object sender, FormClosingEventArgs e)
{
e.Cancel = true;
Hide();
}

**Comment by KedamaOvO** [comment]
Sorry, I don't know what happened.

**Comment by Someone999** [comment]
OK, it's not a problem

**Comment by Someone999** [comment]
Can I get  PPTuple, Stars, etc. in RTPPD?

**Comment by KedamaOvO** [comment]
You can inherit DisplayerBase and then call RegisterDisplayer().
```csharp
//MyDisplayer.cs
class MyDisplayer:DisplayerBase{...}

//other.cs
MyDisplayer _displayer;
rtppd.RegisterDisplayer("my_displayer",(id)=>_displayer = new MyDisplayer());

if(_displayer!=null){
    //do something
   /// _displayer.Pp.RealTimePP
}
```

and add "my_displayer" output method in config

**Comment by Someone999** [comment]
Thanks

**Comment by Someone999** [comment]
Before that , OsuRTDataProvider and RealTimePPDisplayer had been gotten correctly.

**Comment by Someone999** [comment]
new operation code is as same as your's

**Comment by Someone999** [comment]
r.RegisterDisplayer("my", (id) => rt = new RtppdInfo());
                    if(rt is null)
                    {
                        IO.CurrentIO.WriteColor("初始化失败", ConsoleColor.Red);
                        return;
                    }

**Comment by Someone999** [comment]
Why output of my BaseDisplayer inherited class not as smooth as mmf , can I make it smoother ?

**Comment by Someone999** [comment]
In one word, I want to the data updating and display like score window in osu!

**Comment by KedamaOvO** [comment]
Use the **SmoothMath.SmoothDamp(double previousValue, double targetValue, ref double speed, double smoothTime, double dt)** function to achieve smoothing.

```csharp
double speed = 0.0;
SmoothMath.SmoothDamp(value,target_value,ref speed,1.0/60.0);
```csharp

**Comment by Someone999** [comment]
Which namespace I need to use ? I can not find it.

**Comment by Someone999** [comment]
What the difference wit the Damp and DampPPTuple

**Comment by Someone999** [comment]
Only one is value and another one is a struct?

**Comment by Someone999** [comment]
How to fill the para previous value?

**Comment by KedamaOvO** [comment]
```csharp
value = SmoothMath.SmoothDamp(value,target_value,ref speed,1.0/60.0);
```

**Comment by Someone999** [comment]
The three params's type are all PPTuple .I can't understand it by name.

**Comment by Someone999** [comment]
Especially the third one.

**Comment by Someone999** [comment]
How to fill previous_value and how to fill the target ,need I create two object?

**Comment by Someone999** [comment]
And the biggest question is , the third prarm

**Comment by KedamaOvO** [comment]
```csharp
double speed = 0.0;
double value = 0.0;
double target_value =727.0;
public override void FixedUpdate(double time){
    value = SmoothMath.SmoothDamp(value,target_value,ref speed,time);
}
```

**Comment by Someone999** [comment]
Can I use SmoothPPTuple?

**Comment by Someone999** [comment]
And what the targetvalue means

**Comment by KedamaOvO** [comment]
I don't know how to explain it, but you can compile this code to experience it.
```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

public class Program
{
    public static double SmoothDamp(double previousValue, double targetValue, ref double speed, double smoothTime, double dt)
    {
        double t1 = 0.36 * smoothTime;
        double t2 = 0.64 * smoothTime;
        double x = previousValue - targetValue;
        double newSpeed = speed + dt * (-1.0 / (t1 * t2) * x - (t1 + t2) / (t1 * t2) * speed);
        double newValue = x + dt * speed;
        speed = newSpeed;
        double result = targetValue + newValue;
        speed = double.IsNaN(speed) ? 0.0 : speed;
        return double.IsNaN(result) ? 0 : result;
    }

    const double SMOOTH_TIME = 0.50; /*Seconds*/

    public static void Main()
    {

        double target_value = 0;
        double value = 0;
        double speed = 0;
        Task.Run(() => {

            while (true)
            {
                value = SmoothDamp(value, target_value, ref speed, SMOOTH_TIME, 0.033/*Seconds*/);
                Console.Write($"{value:F2}\r");
                Thread.Sleep(33);/*Milliseconds*/
            }
        });

        while (true)
        {
            target_value += 20;
            Thread.Sleep(3000);
        }
    }
}
```

**Comment by Someone999** [comment]
I need do it for every variable or ?

**Comment by Someone999** [comment]
And I noticed that the speed is passing by ref ,Does that mean the speed is a curtain address ?

**Comment by Someone999** [comment]
I get the source to get info of replays , but the code is C++ code ,and used the pointer , I don't know how to deal with it , could you write one plugin to get info of replays or translate it to C Sharp?

**Comment by Someone999** [comment]
class osrString
{
private:
	unsigned int StrLengeh;
	unsigned char Type;
	std::string str;

public:
	operator const char* ()
	{
		return str.c_str();
	}
	std::string string_To_UTF8(const std::string& str)
	{
		int nwLen = ::MultiByteToWideChar(CP_ACP, 0, str.c_str(), -1, NULL, 0);

		wchar_t* pwBuf = new wchar_t[nwLen + 1];//一定要加1，不然会出现尾巴  
		ZeroMemory(pwBuf, nwLen * 2 + 2);

		::MultiByteToWideChar(CP_ACP, 0, str.c_str(), str.length(), pwBuf, nwLen);

		int nLen = ::WideCharToMultiByte(CP_UTF8, 0, pwBuf, -1, NULL, NULL, NULL, NULL);

		char* pBuf = new char[nLen + 1];
		ZeroMemory(pBuf, nLen + 1);

		::WideCharToMultiByte(CP_UTF8, 0, pwBuf, nwLen, pBuf, nLen, NULL, NULL);

		std::string retStr(pBuf);

		delete[]pwBuf;
		delete[]pBuf;

		pwBuf = NULL;
		pBuf = NULL;

		return retStr;
	}
	std::string UTF8_To_string(const std::string& str)
	{
		int nwLen = MultiByteToWideChar(CP_UTF8, 0, str.c_str(), -1, NULL, 0);

		wchar_t* pwBuf = new wchar_t[nwLen + 1];//一定要加1，不然会出现尾巴  
		memset(pwBuf, 0, nwLen * 2 + 2);

		MultiByteToWideChar(CP_UTF8, 0, str.c_str(), str.length(), pwBuf, nwLen);

		int nLen = WideCharToMultiByte(CP_ACP, 0, pwBuf, -1, NULL, NULL, NULL, NULL);

		char* pBuf = new char[nLen + 1];
		memset(pBuf, 0, nLen + 1);

		WideCharToMultiByte(CP_ACP, 0, pwBuf, nwLen, pBuf, nLen, NULL, NULL);

		std::string retStr = pBuf;

		delete[]pBuf;
		delete[]pwBuf;

		pBuf = NULL;
		pwBuf = NULL;

		return retStr;
	}

	osrString()
	{
		Clear();
	}


	~osrString() {}


	void Clear()
	{
		this->Type = 0x00;
		this->StrLengeh = 0;
		this->str = "";
	}

	void Load(std::ifstream& fin)
	{
		fin.read((char*)& Type, sizeof(Type));
		if (Type == 0x00)
		{
			Clear();
		}
		else if (Type == 0x0B)
		{
			//读取StrLengeh（ULEB128）
			unsigned int value = 0;
			byte buff;
			fin.read((char*)& buff, sizeof(buff));

			int offset = 0;
			while (buff != 0) {
				value |= ((buff & 0x7F) << offset); //从低到高将 bits 合并到一起
				offset += 7;
				if ((buff & 0x80) == 0)
					break;
				fin.read((char*)& buff, sizeof(buff));
			}
			StrLengeh = value;

			//读取str
			char* strbuff = new char[StrLengeh + 1];
			ZeroMemory(strbuff, StrLengeh + 1);
			fin.read(strbuff, StrLengeh);

			str = strbuff;

			delete[] strbuff;
			str = UTF8_To_string(str);
		}
	}

	void SetString(std::string str)
	{
		if (!str.empty())
		{
			this->Type = 0x0B;
			this->str = str;
		}
		else {
			this->Type = 0x00;
			this->str = "";
		}
	}

	std::string GetString()
	{
		return this->str;
	}

	void Save(std::ofstream& fout)
	{
		fout.write((char*)& Type, sizeof(Type));
		if (Type == 0x00)
		{
			return;
		}
		else if (Type == 0x0B)
		{
			allspace::Char x = str.c_str();
			std::string utf8_str = string_To_UTF8(str);
			StrLengeh = utf8_str.size();

			//写入StrLengeh（ULEB128）

			unsigned int value = StrLengeh;
			byte buff[5] = { 0 };
			int pos = 0;
			while (value != 0) {
				buff[pos++] = value & 0x7F | 0x80; //每个字节标识信息都设为1
				value >>= 7;
			}
			if (pos > 0)
				buff[pos - 1] &= 0x7F;  //将最后一个字节的标识信息设为0
			fout.write((char*)buff, pos);

			//写入str
			fout.write((char*)utf8_str.c_str(), StrLengeh);
		}
	}
};
public struct OsrData
{
	byte GameMode;              //游戏模式(0 = osu!Standard, 1 = Taiko, 2 = Catch the Beat, 3 = osu!mania)
	int Version;                //创建该回放文件的游戏版本
	osrString beatmapMD5;       //谱面的MD5 hash
	osrString PlayerName;       //玩家名称
	osrString ReplayMD5;        //回放文件的 MD5 hash
	short N300;                 //“300”判定的数量
	short N100;                 //“100”判定（osu!standard），“150”（Taiko），“100”（CTB），“200”（osu!mania）的数量
	short N50;                  //“50”判定（osu!standard）
	short NGeki;                //“激”判定（osu!standard），彩色“300”（osu!mania）的数量
	short NKatu;                //“喝”判定（osu!standard），“100”判定（osu!mania）的数量
	short NMiss;                //Miss的数量
	int TotalScore;             //结算界面显示的总分
	short MaxCombo;             //最大连击数
	byte Perfect;               //Perfect/full combo (1 = 没有Miss和断滑条)
	unsigned int MODs;          //Mods
	osrString LifeBarGraph;     //生命值图像
	__int64 TimeStamp;          //时间戳 DateTime::Ticks
	int ReplayDataLength;       //压缩后的回放数据的字节长度
	byte* ReplayData;           //压缩后的回放数据

	int unknowLength;           //未知数据的长度
	byte UnknowData[8];     //在结尾的未知数据
	void LoadOSR(std::string FileName)
	{
		std::ifstream fin(FileName, std::ios::in | std::ios::binary);
		if (fin.is_open())
		{
			fin.read((char*)& GameMode, sizeof(GameMode));
			fin.read((char*)& Version, sizeof(Version));
			beatmapMD5.Load(fin);
			PlayerName.Load(fin);
			ReplayMD5.Load(fin);
			fin.read((char*)& N300, sizeof(N300));
			fin.read((char*)& N100, sizeof(N100));
			fin.read((char*)& N50, sizeof(N50));
			fin.read((char*)& NGeki, sizeof(NGeki));
			fin.read((char*)& NKatu, sizeof(NKatu));
			fin.read((char*)& NMiss, sizeof(NMiss));
			fin.read((char*)& TotalScore, sizeof(TotalScore));
			fin.read((char*)& MaxCombo, sizeof(MaxCombo));
			fin.read((char*)& Perfect, sizeof(Perfect));
			fin.read((char*)& MODs, sizeof(MODs));
			LifeBarGraph.Load(fin);
			fin.read((char*)& TimeStamp, sizeof(TimeStamp));
			int lzmaLength;
			byte* lzmaData;
			fin.read((char*)& lzmaLength, sizeof(lzmaLength));
			lzmaData = new byte[lzmaLength];
			fin.read((char*)lzmaData, lzmaLength);

			//读取剩下的字节（未知数据）
			unknowLength = 0;
			while (!fin.eof())
			{
				fin.read((char*)& UnknowData[unknowLength++], 1);
			}
		}
		fin.close();
	}
};

**Comment by Someone999** [comment]
I guess the convert between utf8 and string is not needed.

**Comment by KedamaOvO** [comment]
see https://github.com/OsuSync/ReplayPPDisplayer/blob/master/ReplayParser.cs

**Comment by Someone999** [comment]
Though I read that project, but I didn't notice that...

**Comment by Someone999** [comment]
And I had get every Int in replays.

**Comment by Someone999** [comment]
I finally known the BinaryReader read string in this way....

**Comment by Someone999** [comment]
Is there any plugin can calculate the kps(Key per sec)?

**Comment by KedamaOvO** [comment]
No, only OPS(Objects per seconds).

**Comment by Someone999** [comment]
I see.

**Comment by Someone999** [comment]
Another question, how can I use SmoothDampPPTuple() ?

**Comment by Someone999** [comment]
![image](https://user-images.githubusercontent.com/45456778/58432445-f3a3ae00-80e4-11e9-995a-7cab3347ac60.png)
And this, what should I modify?

**Comment by Someone999** [comment]
Real data is larger than this.

**Comment by KedamaOvO** [comment]
Speed ​​does not need to be adjusted.
smoothTime needs to be greater than 0.03.
Dt is the time interval between calls, not time.
