### ISSUE TITLE
Could you help me to find out what let Sync StackOverflow?

### ISSUE THREAD

**Issue by Someone999** [OsuSync/SyncPlugin#31]
Sorry to bother again , this is the source code 
[ConsoleApp1.zip](https://github.com/OsuSync/SyncPlugin/files/3289087/ConsoleApp1.zip)

**Comment by Someone999** [comment]
![image](https://user-images.githubusercontent.com/45456778/59484434-53030b80-8ea4-11e9-918c-811c2663343c.png)

**Comment by Someone999** [comment]
The exception was not thrown after I remove my plugin.

**Comment by Deliay** [comment]
Try debug in VisualStudio debugging mode, when catch the StackOverflowException, see the callstack and find which code call recursived

**Comment by Someone999** [comment]
I had solved that.
